First Spring application
luli25/Spring-API pull request #1
Opened 2021-01-19 21:03 UTC by luli25

2021-01-20 11:09 UTC, gustavopeiretti requested changes

2021-01-20 11:09 UTC, gustavopeiretti commented on src/main/java/com/example/demo/DemoApplication.java
> +		return String.format("Hello %s!", name);
A efectos de tener bien identificadas las diferentes capas de la api separa en paquetes.
Los controladores en un package "controller" y dentro de este agrega una clase DemoController que resuelva el este endpoint.
Lleva la anotacion  RestController a ese controlador.

2021-01-21 18:49 UTC, luli25 commented
Listo

2021-01-21 19:07 UTC, gustavopeiretti approved these changes

2021-01-21 19:09 UTC, merged