Added ClientDto and ClientController
luli25/Spring-API pull request #2
Opened 2021-01-22 21:50 UTC by luli25

2021-01-25 17:48 UTC, gustavopeiretti requested changes

2021-01-25 17:48 UTC, gustavopeiretti commented on src/main/java/com/example/demo/ClientDto.java
> +package com.example.demo;
El paquete para un dto (data tranfer object) podria ser en "model" y dentro de "dto"

Mueve esta clase dentro de model / dto

2021-01-25 17:48 UTC, gustavopeiretti commented on src/main/java/com/example/demo/controller/ClientController.java
> +    public ClientDto clientDto(@RequestParam(value = "name", defaultValue = "NN")String name) {
Puntos a repasar.
- Los diferentes tipos de verbos que existen Get, Post, Put y cual seria el apropiado aqui en vista de tratarse de un insert.
- Como recibir un body json en los parametros del metodo.

2021-01-26 13:55 UTC, luli25 commented on src/main/java/com/example/demo/ClientDto.java
> +package com.example.demo;
Listo

2021-01-28 15:34 UTC, gustavopeiretti approved these changes

2021-01-28 18:31 UTC, merged