Added new attributes to the Client class
luli25/Spring-API pull request #6
Opened 2021-04-05 14:15 UTC by luli25

2021-04-05 18:54 UTC, gustavopeiretti requested changes

2021-04-05 18:54 UTC, gustavopeiretti commented on src/main/java/com/example/demo/controller/ClientController.java
>          clientService.addClient(client);
Los controladores deberian recibir un DTO y no una clase de entidad.  Esto es deuda tecnica que conviene ya ajustar.
EL formato deberia ser propio del DTO porque viene adentro.

2021-04-05 18:54 UTC, gustavopeiretti commented on src/main/java/com/example/demo/model/Client.java
> +    public Client(String name, String lastname, int age, LocalDate birthday) {
No veo quien usa este constructor? Tenes intenciones de usarlo?

2021-04-08 19:52 UTC, luli25 commented on src/main/java/com/example/demo/service/ClientService.java
> +        return entityToDto(clientRepo.save(client));
Modifique el metodo en clientService, al controller tambien tendria que modificarlo??

2021-05-27 18:58 UTC, merged